### PR TITLE
Report coverage from cypress tests

### PR DESCRIPTION
**Pull request by caponetto**
FUP of https://github.com/opendatahub-io/elyra/pull/89

### CODE REVIEW

**Review by paulovmr — APPROVED** [review]

**Comment by jstourac** [comment]
Is there a reason why there are functional code changes as part of this PR for the code coverage reports addition? :thinking:

**Comment by jstourac** [comment]
Yeah, for me it's a code change that should not be part of that PR or at least not the same commit :grinning:

**Comment by jiridanek** [comment]
I liked that it was a self-test for the coverage reporting.

**Comment by jstourac** [comment]
technically... GH doesn't have to be around in the future, sooo... and for us who aren't used to go to GH for this kind of changes... anyway, yeah... we don't need to be that much strict, I agree... we're not flying to Mars anyway...

**Pull request merged**
